# Generated by Django 6.0.4 on 2026-05-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0002_remove_manufacturer_country_alter_car_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
