# Generated by Django 6.0.4 on 2026-05-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0003_car_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
        ),
    ]
