# Generated by Django 6.0.5 on 2026-05-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
