# Generated by Django 6.0.4 on 2026-05-07 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0004_car_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('carro', 'Carros'), ('equipamento', 'Equipamentos Pesados'), ('animal', 'Animais'), ('fazenda', 'Fazenda')], default='carro', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_platform.manufacturer', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
