# Generated by Django 6.0.5 on 2026-05-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_platform", "0004_user_cpf_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
