# Generated by Django 6.0.4 on 2026-05-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0005_car_category_alter_car_manufacturer_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo'),
        ),
    ]
