# Generated by Django 6.0.4 on 2026-05-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0006_alter_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium'), ('destaque', 'Destaque')], default='basico', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('carro', 'Carros'), ('equipamento', 'Equipamentos Pesados'), ('animal', 'Animais'), ('fazenda', 'Fazenda'), ('caminhao', 'Caminhao')], default='carro', max_length=20, verbose_name='Categoria'),
        ),
    ]
