# Generated by Django 6.0.4 on 2026-05-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0007_car_is_paid_car_plan_alter_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
