# Generated by Django 6.0.4 on 2026-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0008_car_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
